name: 'Compile C++'
description: 'This action will compile the C++ program in an appropriate environment.'

inputs:
  cpp-standard:
    description: 'The C++ standard to use.'
    required: true
    default: 'c++14'
  
  cpp-entrypoint:
    description: 'The entrypoint of the C++ program.'
    required: true
    default: 'main.cpp'
  
  output:
    description: 'The output file name.'
    required: true
    default: 'main'
  
  extra-args:
    description: 'Extra arguments to pass to the compiler.'
    required: false
    default: '-O3'

runs:
  using: composite
  steps:
    - name: "Setup GCC"
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x64
    
    - name: "Compile C++"
      shell: bash
      run: g++-9 -Wall -std=${{ inputs.cpp-standard }} ${{ inputs.cpp-entrypoint }} ${{ inputs.extra-args }} -o ${{ inputs.output }}
